config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks do
    resources :users do
      resources :favorites do   
      end
    end
  end

  root to: 'home#index'

  get "bookmarks/index"

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  
  resources :users

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :incoming

  get 'search', to: 'search#search'

end

app/models/bookmark.rb
require 'elasticsearch/model'

class Bookmark < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  default_scope { order('created_at DESC') }

def self.search(query)
  __elasticsearch__.search(
    {
      query: {
        multi_match: {
          query: query,
          fields: ['title^10', 'text']
        }
      },
      highlight: {
        pre_tags: ['<em>'],
        post_tags: ['</em>'],
        fields: {
          title: {},
          text: {}
        }
      }
    }
  )
end

# Delete the previous articles index in Elasticsearch
Bookmark.__elasticsearch__.client.indices.delete index: Bookmark.index_name rescue nil
 
# Create the new index with the new mapping
Bookmark.__elasticsearch__.client.indices.create \
  index: Bookmark.index_name,
  body: { settings: Bookmark.settings.to_hash, mappings: Bookmark.mappings.to_hash }
end 
# Index all article records from the DB to Elasticsearch
Bookmark.import

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @user = current_user
    @bookmark = Bookmark.find(params[:id])
    @favorite = @user.favorites
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
   # @bookmark = Bookmark.new(params.require(:bookmark).permit(:title, :body, :hashtag))
   @bookmark = current_user.bookmarks.build(params.require(:bookmark).permit(:title, :body, :hashtag))
   if @bookmark.save
     flash[:notice] = "Bookmark was saved."
     redirect_to @bookmark
   else
     flash[:error] = "There was an error saving! Please try again."
     render :new
   end
 end

 def edit
   @bookmark = Bookmark.find(params[:id])
 end

 def update
   @bookmark = Bookmark.find(params[:id])
   if @bookmark.update_attributes(params.require(:bookmark).permit(:title, :body, :hashtag))
     flash[:notice] = "Bookmark was updated."
     redirect_to @bookmark
   else
     flash[:error] = "There was an error saving! Please try again."
     render :edit
   end
 end

 def destroy
  @bookmark = Bookmark.find(params[:id])
  name = @bookmark.title

  if @bookmark.destroy
    flash[:notice] = "\"#{name}\" was deleted successfully."
    redirect_to bookmarks_path
  else
    flash[:error] = "There was an error deleting the bookmark."
    render :show
  end
end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/edit.html.erb
 <h1>Edit a Bookmark!</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Suggestions to help others!</p>
     <ul>
       <li>Pick a Relevant #Hashtag</li>
       <li>Keep it on topic!</li>
       <li>No Cat Links!</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @bookmark do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter bookmark description" %>
     </div>
     <div class="form-group">
       <%= f.label :body %>
       <%= f.text_area :body, rows: 2, class: 'form-control', placeholder: "Enter bookmark URL" %>
     </div>
     <div class="form-group">
       <%= f.label :hashtag %>
       <%= f.text_area :hashtag, rows: 1, class: 'form-control', placeholder: "Enter hashtag" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
     <% end %>
   </div>
 </div>

app/views/bookmarks/index.html.erb
<div class="row">
   <div class="tabbable tabs-left">
     <ul class="nav nav-tabs">
       <li class="active"><a href="#bookmarks" data-toggle="tab">Bookmarks</a></li>
       <li><a href="#hashtags" data-toggle="tab">Hashtags</a></li>
     </ul>
     <div class="tab-content">
       <div class="tab-pane active" id="bookmarks">
        <br>
        <p>
          <% @bookmarks.each do |bookmarks| %>
          <%= link_to bookmarks.title, bookmarks %>
          <small>
           Created <%= time_ago_in_words(bookmarks.created_at) %><br/>
         </small>
       </p>
       <% end %>
     </div>
     <div class="tab-pane" id="hashtags">
       <br>
       <p>
        <% @bookmarks.each do |bookmarks| %>
        <%= link_to bookmarks.hashtag, bookmarks %>
      </p>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/bookmarks/new.html.erb
 <h1>Add a Bookmark!</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Suggestions to help others!</p>
     <ul>
       <li>Pick a Relevant #Hashtag</li>
       <li>Keep it on topic!</li>
       <li>No Cat Links!</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @bookmark do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter bookmark description" %>
     </div>
     <div class="form-group">
       <%= f.label :body %>
       <%= f.text_area :body, rows: 2, class: 'form-control', placeholder: "Enter bookmark URL" %>
     </div>
     <div class="form-group">
       <%= f.label :hashtag %>
       <%= f.text_area :hashtag, rows: 1, class: 'form-control', placeholder: "Enter hashtag" %>
     </div>
     <div class="form-group">
       <%= f.submit "Save", class: 'btn btn-success' %>
     </div>
     <% end %>
   </div>
 </div>

app/views/bookmarks/show.html.erb
<h1><%= markdown @bookmark.title %></h1>
<p><%= markdown @bookmark.body %></p>
<p><%= @bookmark.hashtag %></p>
<small>
  <%= image_tag(@bookmark.user.avatar.tiny.url) if @bookmark.user.avatar? %>
  submitted <%= time_ago_in_words(@bookmark.created_at) %> ago by
  <%= @bookmark.user.name %>
</small>
<br>
<br>
<%= link_to "Edit", edit_bookmark_path(@bookmark), class: 'btn btn-success' %>
<%= link_to "Delete Bookmark", [@bookmark], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this bookmark?' } %>

<% favorite = current_user.favorites.where(:bookmark => @bookmark).first %>
<% if favorite.present? %>
<%= link_to bookmark_user_favorite_path(@bookmark, current_user, favorite.id), class: 'btn btn-danger', method: :delete do %>
Unlike

<% end %>
<% else %>
<%= link_to bookmark_user_favorites_path(@bookmark, current_user), class: 'btn btn-primary', method: :create do %>
Like
<% end %>
<% end %>

  