config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks do
    resources :users do
      resources :favorites do   
      end
    end
  end

  root to: 'home#index'

  get "bookmarks/index"

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  
  resources :users

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :incoming

  get 'search', to: 'search#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarx</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
   <ul class="nav nav-tabs">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Bookmarks", bookmarks_path %></li>
    <li><%= link_to "Search", search_path %></li>
    <div class="pull-right user-info">
     <% if current_user %>

Hello <%= link_to (current_user.name || current_user.email), current_user %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
              <span>Edit Profile</span>
            <% end %>

                <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
              <span>Sign Out</span>
            <% end %>

     <% else %>
     <%= link_to "Sign In", new_user_session_path %> or 
     <%= link_to "Sign Up", new_user_registration_path %>
     <% end %>
   </div>
 </ul>

 <% if flash[:notice] %>
 <div class="alert alert-success">
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   <%= flash[:notice] %>
 </div>
 <% elsif flash[:error] %>
 <div class="alert alert-danger">
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   <%= flash[:error] %>
 </div>
 <% elsif flash[:alert] %>
 <div class="alert alert-warning">
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   <%= flash[:alert] %>
 </div>
 <% end %>


 <%= yield %>
</div>
</body>
</html>